# Azure API Credentials
[azure]
AZURE_OPENAI_ENDPOINT = 'https://trashscan-clearpath.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2023-03-15-preview'
AZURE_OPENAI_API_KEY = 'e8f95987636245f3a15398fa040e2972'
